### ISSUE TITLE
测试平台控制台每30秒打印报错信息 Error: Fail at 0

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-project-dzug#224]
```
2019-12-03T03:17:05.143454990Z Error: Fail at 0
2019-12-03T03:17:05.143489475Z     at /app/node_modules/odata-v4-mongodb/node_modules/odata-v4-parser/src/parser.ts:17:28
2019-12-03T03:17:05.143494936Z     at Object.query (/app/node_modules/odata-v4-mongodb/node_modules/odata-v4-parser/src/parser.ts:34:109)
2019-12-03T03:17:05.143498350Z     at Object.createQuery (/app/node_modules/odata-v4-mongodb/lib/index.js:6:66)
2019-12-03T03:17:05.143502332Z     at Object.getObjectList (/app/node_modules/@steedos/core/src/odata/MeteorODataExpressMiddleware.ts:33:46)
2019-12-03T03:17:05.143505716Z     at getObjectList (/app/node_modules/@steedos/core/src/odata/server.ts:16:49)
2019-12-03T03:17:05.143508946Z     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2019-12-03T03:17:05.143512073Z     at next (/app/node_modules/express/lib/router/route.js:137:13)
2019-12-03T03:17:05.143515152Z     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2019-12-03T03:17:05.143518232Z     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2019-12-03T03:17:05.143521491Z     at /app/node_modules/express/lib/router/index.js:281:22
2019-12-03T03:17:05.143524549Z     at param (/app/node_modules/express/lib/router/index.js:354:14)
2019-12-03T03:17:05.143527635Z     at param (/app/node_modules/express/lib/router/index.js:365:14)
2019-12-03T03:17:05.143530639Z     at Function.process_params (/app/node_modules/express/lib/router/index.js:410:3)
2019-12-03T03:17:05.143533635Z     at next (/app/node_modules/express/lib/router/index.js:275:10)
2019-12-03T03:17:05.143536975Z     at /app/node_modules/@steedos/core/src/odata/MeteorODataAPIV4Router.ts:18:9
2019-12-03T03:17:05.143540033Z     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2019-12-03T03:17:05.143543223Z     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2019-12-03T03:17:05.143556155Z     at /app/node_modules/express/lib/router/index.js:284:7
2019-12-03T03:17:05.143559526Z     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2019-12-03T03:17:05.143562599Z     at next (/app/node_modules/express/lib/router/index.js:275:10)
2019-12-03T03:17:05.143565609Z     at setRequestUser (/app/node_modules/@steedos/auth/src/session.ts:266:3)
2019-12-03T03:17:05.143568618Z     at <anonymous>
```

**Comment by sunhaolin** [comment]
```
/creator/api/v4/contract_receipts?$expand=created_by($select=mobile)&$filter=((finished%20ne%20true)%20and%20(created_by%20eq%20'55139f66527eca33d80011ee')&20and%20(due_date%20le%202019-12-10T03:29:45.443Z))
```
此请求导致报错，待MT处理
